# -*- coding: utf-8 -*-
"""PRO-C99-Project-Solution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10tCV5aBeVqjkEvsZwbMR5SgW82KC1x2h

**PRINT MY NAME**
"""

name=(input("Enter your name :  "))
iteration = len(name)
for i in range(0,iteration):
    for j in range(0,iteration):
      if(i==j):
        print(name[j],sep=" ",end=" ")
      else:
        print("*",sep=" ",end=" ")
    print()